import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Room: NextPage = () => {
  return (
    <div className="h-screen bg-primary">
      <Head>
        <title>Everybody is weird</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1 className="text-secondary-primary">Room</h1>
      </main>
    </div>
  );
};

export default Room;
