import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  Layout,
  Navbar,
  Button,
  Input,
  Box,
  Heading,
} from "../../src/components/index";
import { motion } from "framer-motion";
import { SpringTransition, ButtonMotion } from "../../src/constants/index";
import { useForm } from "react-hook-form";

const Room: NextPage = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<FormProps>();
  const onSubmit = handleSubmit((data) => console.log(data));
  return (
    <>
      <Head>
        <title>Everybody is weird Room 1</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Navbar>
          <motion.li
            initial="initial"
            whileHover="hover"
            transition={{
              ...SpringTransition,
            }}
            variants={ButtonMotion}
          >
            <button type="button" className="btn">
              🔨 Leave Room
            </button>
          </motion.li>
        </Navbar>
        <main className="w-full">
          <div className="grid grid-cols-[1fr_minmax(auto,_50%)_1fr] w-full gap-4">
            <div className="flex flex-col gap-4">
              <Box>
                <Heading>Share this game :</Heading>
                <Button type="button" classNames="btn-dark">
                  https://eiw/room/7kale
                </Button>
              </Box>
              <Box>
                <Heading>Chat</Heading>
                <ul className="flex flex-col items-start space-y-2">
                  <li className="flex flex-row space-x-2">
                    <div className="bg-green-500 w-6 h-6 shrink-0"></div>
                    <p className="bg-gray-200 p-1 text-primary font-secondary text-md  rounded-tr-md rounded-br-md rounded-bl-md ">
                      Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                      Quisquam, tempora!
                    </p>
                  </li>
                  <li className="flex flex-row space-x-2">
                    <div className="bg-orange-500 w-6 h-6 shrink-0"></div>
                    <p className="bg-gray-200 p-1 text-primary font-secondary text-md  rounded-tr-md rounded-br-md rounded-bl-md ">
                      Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                      Quisquam, tempora!
                    </p>
                  </li>
                  <li className="flex flex-row-reverse">
                    <div className="bg-purple-500 w-6 h-6 shrink-0 ml-2"></div>
                    <p className="bg-gray-200 p-1 text-primary font-secondary text-md  rounded-tr-md rounded-br-md rounded-bl-md ">
                      Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                      Quisquam, tempora!
                    </p>
                  </li>
                </ul>
                <div className="h-[2px] bg-primary w-full" />
                <div className="w-full">
                  <form
                    onSubmit={onSubmit}
                    className="flex flex-col w-full space-y-2"
                  >
                    <Input
                      dark={true}
                      register={register("message", { required: true })}
                    />

                    <Button classNames="btn-dark" type="submit">
                      💬 Message
                    </Button>
                  </form>
                </div>
              </Box>
            </div>

            <div className="w-full h-[50px] bg-slate-50 "></div>
            <div className="w-full h-auto">
              <div className="flex flex-col gap-4">
                <Box>
                  <Heading>Players</Heading>
                  <ul className="flex flex-col items-start space-y-2">
                    <li className="flex flex-row space-x-2">
                      <div className="bg-green-500 w-6 h-6 shrink-0"></div>
                      <p className=" text-primary font-secondary text-md  rounded-tr-md rounded-br-md rounded-bl-md ">
                        Marcellus
                      </p>
                    </li>
                    <li className="flex flex-row space-x-2">
                      <div className="bg-orange-500 w-6 h-6 shrink-0"></div>
                      <p className=" text-primary font-secondary text-md  rounded-tr-md rounded-br-md rounded-bl-md ">
                        Sehriban
                      </p>
                    </li>
                  </ul>
                </Box>
                <Box>
                  <Heading>Question</Heading>

                  <p className=" bg-tertiary-primary text-primary font-secondary text-md rounded-md p-2">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                    Omnis, totam.?
                  </p>
                  <div className="h-[2px] bg-primary w-full" />
                  <div className="w-full">
                    <form
                      onSubmit={onSubmit}
                      className="flex flex-col w-full space-y-2"
                    >
                      <Input
                        dark={true}
                        register={register("message", { required: true })}
                      />

                      <Button classNames="btn-dark" type="submit">
                        ✍ Answer
                      </Button>
                    </form>
                  </div>
                </Box>
              </div>
            </div>
          </div>
        </main>
      </Layout>
    </>
  );
};

export default Room;
