import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Layout, Navbar } from "../src/components/index";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Everybody is weird</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Navbar>
          <motion.li
            initial={{ scale: 1 }}
            whileHover={{ scale: 1.1 }}
            transition={{
              type: "spring",
              duration: 1,
              bounce: 0.75,
            }}
          >
            <Link href="/rooms" passHref>
              <a className="bg-slate-50 text-primary font-primary text-xl px-6 py-2 rounded-md inline-flex">
                📦 All Rooms
              </a>
            </Link>
          </motion.li>
          <motion.li
            initial={{ scale: 1 }}
            whileHover={{ scale: 1.1 }}
            transition={{
              type: "spring",
              duration: 1,
              bounce: 0.75,
            }}
          >
            <button className="bg-slate-50 text-primary font-primary text-xl px-6 py-2 rounded-md">
              🔨 Create Lobby
            </button>
          </motion.li>
        </Navbar>
      </Layout>
    </>
  );
};

export default Home;
