import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Layout } from "../src/components/index";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Everybody is weird</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        
      </Layout>
    </>
  );
};

export default Home;
